version: '3.8'

services:
  rzdatabase:
    image: mysql:8.3.0
    container_name: rzdatabase
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb-volume:/var/lib/mysql
      #- ./conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init-01.sql
      - ./conf/spring_batch.sql:/docker-entrypoint-initdb.d/init-02.sql
      - ./conf/data.sql:/docker-entrypoint-initdb.d/init-03.sql
    env_file:
      - ./conf/mysql-vars.env

volumes:
  mysqldb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jenkins/var/lib/mysql
